import React, { useState } from 'react';
import { useLanguage } from '../context/LanguageContext';
import { DataSourceBadge } from '../components/DataSourceBadge';
import { RiskMeter } from '../components/RiskMeter';
import { CloudRain, Wind, Droplets, Thermometer, CloudLightning, AlertOctagon, Info, CheckCircle2 } from 'lucide-react';

export const WeatherForecast: React.FC = () => {
  const { t } = useLanguage();
  const [selectedLocation, setSelectedLocation] = useState('Kedarnath Valley (Uttarakhand)');

  const locations = [
    'Kedarnath Valley (Uttarakhand)',
    'North Sikkim (Sikkim)',
    'Kullu Valley (Himachal Pradesh)',
    'Dima Hasao (Assam)',
    'Shillong (Meghalaya)'
  ];

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900">{t('weatherTitle')}</h1>
          <p className="text-slate-500 text-sm">AI Weather Telemetry & Explainable Flash Flood Forecasting</p>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={selectedLocation}
            onChange={(e) => setSelectedLocation(e.target.value)}
            className="bg-white border border-slate-200 text-sm font-bold text-slate-800 rounded-xl px-3 py-2 outline-none shadow-sm cursor-pointer"
          >
            {locations.map((loc) => (
              <option key={loc} value={loc}>{loc}</option>
            ))}
          </select>
          <DataSourceBadge status="SIMULATED" lastUpdated="Updated 3 mins ago" />
        </div>
      </div>

      {/* Distinction Banner */}
      <div className="bg-sky-50 border border-sky-200 rounded-2xl p-4 flex items-center justify-between text-xs text-sky-900 shadow-sm">
        <div className="flex items-center gap-2">
          <Info className="w-5 h-5 text-sky-600 shrink-0" />
          <span><strong>Notice:</strong> System advisory scores are generated by multi-parameter rule engines. Official meteorological alerts originate exclusively from IMD / CWC bulletins.</span>
        </div>
        <span className="font-bold bg-sky-200/80 px-2.5 py-1 rounded-md text-[10px] uppercase tracking-wider shrink-0 ml-2">DEMO FEED</span>
      </div>

      {/* Flash Flood Risk Block */}
      <div className="bg-white border-2 border-red-200 rounded-2xl shadow-lg p-6 flex flex-col md:flex-row gap-8 items-start md:items-center relative overflow-hidden">
        <div className="absolute top-0 right-0 bg-red-600 text-white font-extrabold text-[10px] px-3 py-1 rounded-bl-xl tracking-wider uppercase">
          System-Generated Advisory
        </div>

        <div className="flex flex-col items-center justify-center shrink-0 w-36">
          <div className="text-xs font-bold text-slate-500 mb-1 uppercase tracking-wider text-center">Flash Flood<br/>Risk Score</div>
          <div className="text-5xl font-black text-red-600 mb-3">84 / 100</div>
          <RiskMeter level="VERY HIGH" size="sm" />
        </div>
        
        <div className="flex-1 space-y-4 border-t md:border-t-0 md:border-l border-slate-100 pt-4 md:pt-0 md:pl-8">
          <div>
            <span className="inline-block px-2.5 py-1 bg-red-100 text-red-700 rounded-full text-[11px] font-extrabold uppercase tracking-wider mb-2 border border-red-200">
              High Flash Flood Probability
            </span>
            <h3 className="font-extrabold text-slate-900 text-lg">High Probability of sudden river rise and canyon flash flood in next 6-12 hours.</h3>
          </div>
          
          <div className="space-y-1.5 text-xs text-slate-700">
            <p className="font-bold text-slate-800 uppercase tracking-wider text-[11px]">Primary Contributing Causes:</p>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <li className="flex items-center gap-2 bg-slate-50 p-2 rounded-lg border border-slate-200">
                <AlertOctagon className="w-4 h-4 text-red-500 shrink-0" />
                <span>Heavy localized rainfall (<strong>55 mm in 3h</strong>)</span>
              </li>
              <li className="flex items-center gap-2 bg-slate-50 p-2 rounded-lg border border-slate-200">
                <AlertOctagon className="w-4 h-4 text-red-500 shrink-0" />
                <span>Extremely high soil saturation (<strong>88%</strong>)</span>
              </li>
              <li className="flex items-center gap-2 bg-slate-50 p-2 rounded-lg border border-slate-200">
                <AlertOctagon className="w-4 h-4 text-red-500 shrink-0" />
                <span>Funneling steep terrain slope runoff</span>
              </li>
              <li className="flex items-center gap-2 bg-slate-50 p-2 rounded-lg border border-slate-200">
                <AlertOctagon className="w-4 h-4 text-red-500 shrink-0" />
                <span>River Gauge rise rate exceeding <strong>0.4 m/hr</strong></span>
              </li>
            </ul>
          </div>
          
          <div className="bg-red-50 p-3.5 rounded-xl border border-red-200 space-y-1">
            <p className="text-xs font-bold text-red-800 uppercase tracking-wider">Recommended Action:</p>
            <p className="text-xs text-red-700 font-semibold leading-relaxed">
              "Residents in lower riverbanks and ravine funnels should remain prepared for immediate evacuation to designated safe high ground. Avoid stream crossings and unpaved mountain roads."
            </p>
          </div>
        </div>
      </div>

      {/* Current Conditions */}
      <h2 className="text-lg font-black text-slate-900 pt-2">Live Weather Sensor Telemetry</h2>
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex flex-col items-center justify-center gap-2">
          <Thermometer className="w-6 h-6 text-orange-500" />
          <span className="text-2xl font-black text-slate-800">22°C</span>
          <span className="text-xs font-bold text-slate-500 uppercase">Temperature</span>
        </div>
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex flex-col items-center justify-center gap-2">
          <CloudRain className="w-6 h-6 text-blue-500" />
          <span className="text-2xl font-black text-slate-800">18.5 mm</span>
          <span className="text-xs font-bold text-slate-500 uppercase">Rainfall / hr</span>
        </div>
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex flex-col items-center justify-center gap-2">
          <Droplets className="w-6 h-6 text-cyan-500" />
          <span className="text-2xl font-black text-slate-800">92%</span>
          <span className="text-xs font-bold text-slate-500 uppercase">Humidity</span>
        </div>
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex flex-col items-center justify-center gap-2">
          <Wind className="w-6 h-6 text-slate-500" />
          <span className="text-2xl font-black text-slate-800">24 km/h</span>
          <span className="text-xs font-bold text-slate-500 uppercase">Wind Velocity</span>
        </div>
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex flex-col items-center justify-center gap-2">
          <CloudLightning className="w-6 h-6 text-amber-500" />
          <span className="text-2xl font-black text-slate-800">80%</span>
          <span className="text-xs font-bold text-slate-500 uppercase">T-Storm Prob.</span>
        </div>
      </div>

      {/* Forecast Timeline */}
      <h2 className="text-lg font-black text-slate-900 pt-2">Rainfall & Flood Forecast Timeline</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { time: 'Next 3 Hours', rain: '55 mm', intensity: 'Heavy Downpour', level: 'HIGH' },
          { time: 'Next 6 Hours', rain: '70 mm', intensity: 'Torrential Peak', level: 'VERY HIGH' },
          { time: 'Next 12 Hours', rain: '25 mm', intensity: 'Moderate Rain', level: 'MODERATE' },
          { time: 'Next 24 Hours', rain: '10 mm', intensity: 'Light Showers', level: 'LOW' }
        ].map((f, i) => (
          <div key={i} className="bg-white border border-slate-200 rounded-2xl p-5 flex flex-col items-center text-center gap-3 shadow-md">
            <span className="font-bold text-slate-700 bg-slate-100 px-3 py-1 rounded-full border border-slate-200 text-xs shadow-xs">{f.time}</span>
            <div className="space-y-1">
              <CloudRain className={`w-9 h-9 mx-auto ${f.level === 'VERY HIGH' ? 'text-red-500' : f.level === 'HIGH' ? 'text-orange-500' : 'text-blue-500'}`} />
              <div className="font-black text-2xl text-slate-900">{f.rain}</div>
              <div className="text-xs font-semibold text-slate-500">{f.intensity}</div>
            </div>
            <RiskMeter level={f.level as any} size="sm" />
          </div>
        ))}
      </div>
    </div>
  );
};
