import { DistrictAlert, MonitoringStation, RescueTeam, RiskZone, SOSIncident } from './types.js';

export const initialStations: MonitoringStation[] = [
  {
    id: 'ST-101',
    name: 'Trishuli Gorge River Gauge',
    type: 'RIVER_GAUGE',
    riverName: 'Trishuli River',
    district: 'Nuwakot',
    location: { lat: 27.912, lng: 85.165, elevation: 620 },
    waterLevel: 5.4,
    warningLevel: 4.8,
    dangerLevel: 6.0,
    riseRate: 1.25,
    rainfall: 62.5,
    temperature: 18.4,
    humidity: 92,
    windSpeed: 22,
    soilMoisture: 88,
    slopeGradient: 34,
    valleyNarrowness: 1.8,
    riskScore: 0.84,
    riskLevel: 'SEVERE',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(5.4, 62.5),
  },
  {
    id: 'ST-102',
    name: 'Bhotekoshi Hydro Basin Gauge',
    type: 'RIVER_GAUGE',
    riverName: 'Bhote Koshi',
    district: 'Sindhupalchok',
    location: { lat: 27.876, lng: 85.892, elevation: 1350 },
    waterLevel: 6.1,
    warningLevel: 5.0,
    dangerLevel: 5.8,
    riseRate: 1.85,
    rainfall: 78.0,
    temperature: 15.2,
    humidity: 96,
    windSpeed: 28,
    soilMoisture: 94,
    slopeGradient: 38,
    valleyNarrowness: 2.1,
    riskScore: 0.93,
    riskLevel: 'SEVERE',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(6.1, 78.0),
  },
  {
    id: 'ST-103',
    name: 'Marshyangdi Valley Station',
    type: 'RIVER_GAUGE',
    riverName: 'Marshyangdi River',
    district: 'Lamjung',
    location: { lat: 28.214, lng: 84.375, elevation: 790 },
    waterLevel: 3.8,
    warningLevel: 4.2,
    dangerLevel: 5.2,
    riseRate: 0.65,
    rainfall: 38.0,
    temperature: 20.1,
    humidity: 84,
    windSpeed: 14,
    soilMoisture: 72,
    slopeGradient: 26,
    valleyNarrowness: 1.4,
    riskScore: 0.58,
    riskLevel: 'HIGH',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(3.8, 38.0),
  },
  {
    id: 'ST-104',
    name: 'Sunkoshi Hydro Station',
    type: 'RIVER_GAUGE',
    riverName: 'Sun Koshi',
    district: 'Sindhupalchok',
    location: { lat: 27.682, lng: 85.731, elevation: 840 },
    waterLevel: 4.5,
    warningLevel: 4.5,
    dangerLevel: 5.5,
    riseRate: 0.95,
    rainfall: 48.0,
    temperature: 17.8,
    humidity: 89,
    windSpeed: 18,
    soilMoisture: 82,
    slopeGradient: 31,
    valleyNarrowness: 1.6,
    riskScore: 0.72,
    riskLevel: 'HIGH',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(4.5, 48.0),
  },
  {
    id: 'ST-105',
    name: 'Bagmati Chobar Gorge Monitor',
    type: 'RIVER_GAUGE',
    riverName: 'Bagmati River',
    district: 'Kathmandu',
    location: { lat: 27.665, lng: 85.291, elevation: 1280 },
    waterLevel: 3.2,
    warningLevel: 3.8,
    dangerLevel: 4.8,
    riseRate: 0.40,
    rainfall: 24.0,
    temperature: 21.0,
    humidity: 76,
    windSpeed: 10,
    soilMoisture: 65,
    slopeGradient: 18,
    valleyNarrowness: 1.2,
    riskScore: 0.41,
    riskLevel: 'MODERATE',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(3.2, 24.0),
  },
  {
    id: 'ST-106',
    name: 'Seti River Canyon Sensor',
    type: 'RIVER_GAUGE',
    riverName: 'Seti Gandaki',
    district: 'Kaski',
    location: { lat: 28.232, lng: 83.991, elevation: 860 },
    waterLevel: 2.1,
    warningLevel: 3.5,
    dangerLevel: 4.5,
    riseRate: 0.15,
    rainfall: 12.0,
    temperature: 23.5,
    humidity: 62,
    windSpeed: 8,
    soilMoisture: 55,
    slopeGradient: 24,
    valleyNarrowness: 1.5,
    riskScore: 0.22,
    riskLevel: 'LOW',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(2.1, 12.0),
  },
  {
    id: 'ST-107',
    name: 'Melamchi Ridge Met Station',
    type: 'WEATHER_STATION',
    district: 'Sindhupalchok',
    location: { lat: 27.833, lng: 85.581, elevation: 1540 },
    waterLevel: 0,
    warningLevel: 0,
    dangerLevel: 0,
    riseRate: 0,
    rainfall: 82.0,
    temperature: 14.1,
    humidity: 98,
    windSpeed: 32,
    soilMoisture: 96,
    slopeGradient: 40,
    valleyNarrowness: 2.0,
    riskScore: 0.88,
    riskLevel: 'SEVERE',
    status: 'ONLINE',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(0, 82.0),
  },
  {
    id: 'ST-108',
    name: 'Kali Gandaki Dam Outlook',
    type: 'RIVER_GAUGE',
    riverName: 'Kali Gandaki',
    district: 'Mustang',
    location: { lat: 28.784, lng: 83.722, elevation: 2720 },
    waterLevel: 2.8,
    warningLevel: 3.8,
    dangerLevel: 4.6,
    riseRate: 0.20,
    rainfall: 14.0,
    temperature: 12.0,
    humidity: 58,
    windSpeed: 24,
    soilMoisture: 48,
    slopeGradient: 22,
    valleyNarrowness: 1.3,
    riskScore: 0.28,
    riskLevel: 'LOW',
    status: 'WARNING',
    lastUpdated: new Date().toISOString(),
    telemetryHistory: generateTelemetryHistory(2.8, 14.0),
  },
];

export const initialZones: RiskZone[] = [
  {
    id: 'ZONE-SIN',
    name: 'Bhotekoshi & Melamchi Corridor',
    district: 'Sindhupalchok',
    coordinates: [
      [27.92, 85.80],
      [27.95, 85.95],
      [27.75, 85.98],
      [27.72, 85.70],
    ],
    elevationAvg: 1450,
    slopeGradientAvg: 38,
    populationDensity: 320,
    totalPopulation: 45000,
    riskScore: 0.91,
    riskLevel: 'SEVERE',
    primaryRiskFactors: [
      'Active Cloudburst anomaly (>78mm/h)',
      'Sudden Bhotekoshi water rise (1.85 m/h)',
      'Saturated steep slopes (>94% soil saturation)',
    ],
    safeEvacuationPoint: {
      name: 'Chautara Ridge High-Ground Evacuation Center',
      lat: 27.778,
      lng: 85.718,
      capacity: 3500,
    },
  },
  {
    id: 'ZONE-NUW',
    name: 'Trishuli River Valley',
    district: 'Nuwakot',
    coordinates: [
      [27.98, 85.10],
      [27.96, 85.25],
      [27.85, 85.24],
      [27.87, 85.08],
    ],
    elevationAvg: 850,
    slopeGradientAvg: 32,
    populationDensity: 410,
    totalPopulation: 38000,
    riskScore: 0.82,
    riskLevel: 'SEVERE',
    primaryRiskFactors: [
      'Water level exceeding warning mark',
      'High valley narrowness surge multiplier',
    ],
    safeEvacuationPoint: {
      name: 'Bidur Stadium & Helipad Safe Zone',
      lat: 27.905,
      lng: 85.155,
      capacity: 4200,
    },
  },
  {
    id: 'ZONE-KTM',
    name: 'Upper Bagmati & Chobar Valley',
    district: 'Kathmandu',
    coordinates: [
      [27.72, 85.26],
      [27.74, 85.35],
      [27.63, 85.34],
      [27.62, 85.27],
    ],
    elevationAvg: 1300,
    slopeGradientAvg: 18,
    populationDensity: 2800,
    totalPopulation: 220000,
    riskScore: 0.45,
    riskLevel: 'MODERATE',
    primaryRiskFactors: ['Moderate rainfall runoff', 'Urban drainage bottleneck'],
    safeEvacuationPoint: {
      name: 'Kirtipur Hillside Disaster Shelter',
      lat: 27.681,
      lng: 85.278,
      capacity: 8000,
    },
  },
  {
    id: 'ZONE-LAM',
    name: 'Marshyangdi Hydro Catchment',
    district: 'Lamjung',
    coordinates: [
      [28.28, 84.30],
      [28.26, 84.45],
      [28.15, 84.42],
      [28.16, 84.28],
    ],
    elevationAvg: 920,
    slopeGradientAvg: 28,
    populationDensity: 210,
    totalPopulation: 28000,
    riskScore: 0.61,
    riskLevel: 'HIGH',
    primaryRiskFactors: ['Upstream heavy rainfall', 'Soil saturation at 72%'],
    safeEvacuationPoint: {
      name: 'Besisahar Community Ground',
      lat: 28.232,
      lng: 84.378,
      capacity: 2500,
    },
  },
];

export const initialIncidents: SOSIncident[] = [
  {
    id: 'SOS-901',
    citizenName: 'Pema Sherpa',
    phone: '+977 9841234567',
    location: {
      lat: 27.882,
      lng: 85.885,
      addressDescription: 'Near Tatopani Bazaar bridge, flood water rising into house ground floor',
    },
    headcount: 6,
    medicalUrgency: 'CRITICAL',
    note: 'River broke embankment. Elderly person with breathing difficulty needs urgent medical evacuation.',
    mode: 'SATELLITE',
    packetSizeCompressedBytes: 142,
    status: 'RECEIVED',
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    zoneId: 'ZONE-SIN',
    zoneName: 'Bhotekoshi & Melamchi Corridor',
    district: 'Sindhupalchok',
    priorityScore: 215,
    commsLog: [
      {
        id: 'c1',
        sender: 'Pema Sherpa',
        role: 'CITIZEN',
        message: 'SOS triggered via Satellite. Water rising 1m/h.',
        timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
      },
      {
        id: 'c2',
        sender: 'Command Dispatch',
        role: 'COMMAND_CENTER',
        message: 'Signal received via Garmin Satellite Relay. Rescue Team Alpha alerted.',
        timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
      },
    ],
  },
  {
    id: 'SOS-902',
    citizenName: 'Ram Bahadur Thapa',
    phone: '+977 9812987654',
    location: {
      lat: 27.915,
      lng: 85.168,
      addressDescription: 'Trishuli Riverbank settlement near Hydro Intake',
    },
    headcount: 12,
    medicalUrgency: 'HIGH',
    note: 'Trapped on concrete rooftop, 12 people including 4 children.',
    mode: 'STANDARD',
    packetSizeCompressedBytes: 420,
    status: 'DISPATCHED',
    assignedTeamId: 'TEAM-01',
    assignedTeamName: 'Himalayan Air Rescue Taskforce (Helicopter)',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    zoneId: 'ZONE-NUW',
    zoneName: 'Trishuli River Valley',
    district: 'Nuwakot',
    priorityScore: 195,
    commsLog: [
      {
        id: 'c3',
        sender: 'Ram Bahadur Thapa',
        role: 'CITIZEN',
        message: 'Water cut off main road. Need winching support.',
        timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
      },
      {
        id: 'c4',
        sender: 'Team Alpha Capt. Gurung',
        role: 'RESCUE_TEAM',
        message: 'Helicopter airborne. Estimated arrival 7 mins.',
        timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
      },
    ],
  },
  {
    id: 'SOS-903',
    citizenName: 'Maya Tamang',
    phone: '+977 9803112233',
    location: {
      lat: 27.841,
      lng: 85.590,
      addressDescription: 'Melamchi Bazaar lower market',
    },
    headcount: 4,
    medicalUrgency: 'MEDIUM',
    note: 'Mudslide blocking back exit. Water entering shop.',
    mode: 'SATELLITE',
    packetSizeCompressedBytes: 118,
    status: 'SATELLITE_RELAY',
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    zoneId: 'ZONE-SIN',
    zoneName: 'Bhotekoshi & Melamchi Corridor',
    district: 'Sindhupalchok',
    priorityScore: 160,
    commsLog: [
      {
        id: 'c5',
        sender: 'Maya Tamang',
        role: 'CITIZEN',
        message: 'Sent low-power SOS via Satellite node #412.',
        timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
      },
    ],
  },
];

export const initialRescueTeams: RescueTeam[] = [
  {
    id: 'TEAM-01',
    name: 'Himalayan Air Rescue Taskforce (Helicopter)',
    unitLeader: 'Capt. Bikram Gurung',
    contactNumber: '+977 9851099881',
    status: 'EN_ROUTE',
    currentLocation: { lat: 27.900, lng: 85.160 },
    assignedIncidentId: 'SOS-902',
    capacity: 15,
    vehicleType: 'HELICOPTER',
  },
  {
    id: 'TEAM-02',
    name: 'Sindhupalchok Rapid Disaster Response (Boat & Winch)',
    unitLeader: 'Lt. Sunita Rai',
    contactNumber: '+977 9851099882',
    status: 'AVAILABLE',
    currentLocation: { lat: 27.778, lng: 85.718 },
    capacity: 20,
    vehicleType: 'BOAT',
  },
  {
    id: 'TEAM-03',
    name: 'Nuwakot Armed Police Disaster Unit',
    unitLeader: 'Inspector Rajesh KC',
    contactNumber: '+977 9851099883',
    status: 'ON_SITE',
    currentLocation: { lat: 27.912, lng: 85.165 },
    capacity: 30,
    vehicleType: 'ALL_TERRAIN_TRUCK',
  },
];

export const initialAlerts: DistrictAlert[] = [
  {
    id: 'ALERT-801',
    district: 'Sindhupalchok',
    severity: 'SEVERE',
    title: 'RED ALERT: Flash Flood & Debris Flow Imminent in Bhotekoshi Valley',
    message: 'Extreme cloudburst recorded (>78mm/h). Bhotekoshi river level rising at 1.85m/h. Residents in riverside settlements must immediately move to designated high ground shelters.',
    recommendedAction: 'EVACUATE IMMEDIATELY to Chautara Ridge High-Ground Shelter.',
    issuedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 12 * 3600000).toISOString(),
    active: true,
    isManualOverride: false,
    issuedBy: 'FloodGuard Automated Risk Algorithm',
  },
  {
    id: 'ALERT-802',
    district: 'Nuwakot',
    severity: 'SEVERE',
    title: 'CRITICAL ALERT: Trishuli River Surge Exceeds Danger Mark',
    message: 'Trishuli River water gauge has reached 5.4m (Danger Level: 6.0m). Heavy runoff upstream poses high risk to lower bridge settlements.',
    recommendedAction: 'Move livestock and vehicles above 700m elevation mark.',
    issuedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 10 * 3600000).toISOString(),
    active: true,
    isManualOverride: false,
    issuedBy: 'Nuwakot District Emergency Operation Center',
  },
];

function generateTelemetryHistory(currentWater: number, currentRain: number) {
  const history = [];
  const now = Date.now();
  for (let i = 24; i >= 0; i--) {
    const time = new Date(now - i * 3600000).toISOString();
    const factor = (24 - i) / 24;
    const water = Math.max(0.5, Number((currentWater * (0.4 + 0.6 * factor) + (Math.random() - 0.5) * 0.2).toFixed(2)));
    const rain = Math.max(0, Number((currentRain * (0.3 + 0.7 * factor) + (Math.random() - 0.5) * 4).toFixed(1)));
    const soil = Math.min(100, Math.round(50 + 45 * factor));
    history.push({
      timestamp: time,
      waterLevel: water,
      rainfall: rain,
      soilMoisture: soil,
    });
  }
  return history;
}
